# Generated by Django 5.2.8 on 2025-11-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
